spring:
    application:
        name: filestorageservice
springdoc: 
    swagger-ui: 
        path: / 
    api-docs: 
        path: /v3/api-docs
server:
    port: 8282

# /app/filestorage/images/
file:
  upload-img-dir: /srv/nfs_shared/images/
  upload-img-client: /images/**
  upload-file-dir: /srv/nfs_shared/data/